[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pdfplumber>=0.11.7",
    "reportlab>=4.4.2",
    "streamlit>=1.46.0",
]
